### ISSUE TITLE
ctx.imageSmoothingEnabled is always true

### ISSUE THREAD

**Issue by Sgajjar08** [santilland/plotty#26] opened 2020-09-21 11:01 UTC
Hello there,

I am using plotty to load raster(tiff) image on the map but I see that the image smoothing is always being true, do you know how can I make it false?

`let image = await this.fetchGeoTiffImage(cropPathObject)
    let rasters = await image.readRasters()
    let bbox = image.getBoundingBox()
    let bitmapCanvas = this.refs.myCanvas
    let band0 = rasters[0]
    let band1 = rasters[1]
    let bandF = new Float32Array(band0)

    for (let i = 0; i < band0.length; i++) {
      if (band1[i] < 75) {
        bandF[i] = NaN
      }
    }

    this.min = Math.min.apply(null, bandF.filter(x => !isNaN(x)))
    this.max = Math.max.apply(null, bandF.filter(x => !isNaN(x)))

    let plotLayer = new plotty.plot({
      canvas: bitmapCanvas,
      useWebGL: false,
      data: this.state.bandFView ? bandF : band0,
      width: image.getWidth(),
      height: image.getHeight(),
      domain: [this.min, this.max],
      colorScale: 'viridis',
    })
    plotLayer.render()`

**Comment by santilland** [comment] 2020-09-21 13:10
Hello Sgajjar08,
this is not something related to plotty, plotty will output to the canvas in the size specified, without scaling, "smoothing" will only be applied if the rendered image is then stretched and rendered somewhere else (or you are manipulating the canvas with css styles), probably with the map library you are using.
Some map libraries will allow you to set the scaling type, the default is usually linear interpolation which makes it "smooth", you would want to use nearest neighbor interpolation for "sharp" edges.
So this is probably a question directed to whatever mapping library you are using.

**Comment by Sgajjar08** [comment] 2020-09-21 13:15
Ok @santilland,
I will look into it. Thank you so much for your help.

**Comment by santilland** [comment] 2020-09-21 13:17
No problem, hope you can find the issue. I will close this ticket now, if you find out the issue is related to plotty or have another question feel free to reopen the ticket or create a new one.

**Closed by santilland** 2020-09-21 13:17 UTC
